#!/usr/bin/env python3
"""Analyze categorized Amazon order CSVs generated by the ingestion pipeline."""

import argparse
import csv
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_WORKDIR = "amazon-history-categorized"


def clean(value):
    return str(value or "").strip()


def truthy(value):
    return clean(value).lower() in {"1", "true", "yes", "y"}


def parse_year(path):
    stem = path.stem
    try:
        return int(stem.rsplit("-", 1)[1])
    except (IndexError, ValueError):
        return None


def parse_date(value):
    text = clean(value)
    if not text:
        return None
    if "T" in text:
        text = text.split("T", 1)[0]
    for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%Y/%m/%d"):
        try:
            return datetime.strptime(text[:10], fmt).date()
        except ValueError:
            continue
    return None


def parse_amount(value):
    text = clean(value)
    if not text or text in {"Not Available", "Not Applicable", "No Refund"}:
        return None
    text = text.replace("$", "").replace(",", "").replace("'", "")
    try:
        return float(text)
    except ValueError:
        return None


def row_amount(row):
    for column in ("Total Amount", "Transaction Amount", "Price", "Shipment Item Subtotal", "Unit Price"):
        amount = parse_amount(row.get(column))
        if amount is not None:
            return amount
    return 0.0


def category_level(category, depth):
    text = clean(category) or "Other / Uncategorized"
    parts = [part.strip() for part in text.split(" > ") if part.strip()]
    if not parts:
        return "Other / Uncategorized"
    return " > ".join(parts[:depth])


def order_id(row):
    return clean(row.get("Order ID") or row.get("Digital Order Item ID") or row.get("Digital Order ID"))


def iter_rows(workdir, start_year, end_year, include_returned):
    orders_dir = workdir / "orders"
    for path in sorted(orders_dir.glob("orders-*.csv")):
        source_year = parse_year(path)
        if source_year is None:
            continue
        if start_year and source_year < start_year:
            continue
        if end_year and source_year > end_year:
            continue
        with path.open(newline="", encoding="utf-8-sig") as csv_file:
            reader = csv.DictReader(csv_file)
            for row in reader:
                if not include_returned and truthy(row.get("is_returned")):
                    continue
                order_date = parse_date(row.get("source_order_date") or row.get("Order Date"))
                year = order_date.year if order_date else source_year
                if start_year and year < start_year:
                    continue
                if end_year and year > end_year:
                    continue
                yield path, year, row


def build_summary(workdir, start_year, end_year, include_returned, depth):
    by_category = defaultdict(lambda: {"spend": 0.0, "rows": 0, "orders": set(), "years": defaultdict(float)})
    by_year = defaultdict(lambda: {"spend": 0.0, "rows": 0, "orders": set()})
    by_source = defaultdict(lambda: {"spend": 0.0, "rows": 0})
    totals = {"spend": 0.0, "rows": 0, "orders": set(), "returned_excluded": not include_returned}
    files = set()

    for path, year, row in iter_rows(workdir, start_year, end_year, include_returned):
        files.add(path.name)
        amount = row_amount(row)
        category = category_level(row.get("category"), depth)
        oid = order_id(row)
        source = clean(row.get("source_type")) or "unknown"

        totals["spend"] += amount
        totals["rows"] += 1
        if oid:
            totals["orders"].add(oid)

        by_category[category]["spend"] += amount
        by_category[category]["rows"] += 1
        by_category[category]["years"][str(year)] += amount
        if oid:
            by_category[category]["orders"].add(oid)

        by_year[str(year)]["spend"] += amount
        by_year[str(year)]["rows"] += 1
        if oid:
            by_year[str(year)]["orders"].add(oid)

        by_source[source]["spend"] += amount
        by_source[source]["rows"] += 1

    category_rows = []
    total_spend = totals["spend"]
    for category, stats in by_category.items():
        category_rows.append(
            {
                "category": category,
                "spend": round(stats["spend"], 2),
                "share": round((stats["spend"] / total_spend * 100) if total_spend else 0, 2),
                "rows": stats["rows"],
                "orders": len(stats["orders"]),
                "years": {year: round(amount, 2) for year, amount in sorted(stats["years"].items())},
            }
        )
    category_rows.sort(key=lambda row: row["spend"], reverse=True)

    year_rows = [
        {
            "year": year,
            "spend": round(stats["spend"], 2),
            "rows": stats["rows"],
            "orders": len(stats["orders"]),
        }
        for year, stats in sorted(by_year.items())
    ]
    source_rows = [
        {"source_type": source, "spend": round(stats["spend"], 2), "rows": stats["rows"]}
        for source, stats in sorted(by_source.items(), key=lambda item: item[1]["spend"], reverse=True)
    ]

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "workdir": str(workdir),
        "start_year": start_year,
        "end_year": end_year,
        "include_returned": include_returned,
        "category_depth": depth,
        "source_files": sorted(files),
        "totals": {
            "spend": round(totals["spend"], 2),
            "rows": totals["rows"],
            "orders": len(totals["orders"]),
            "returned_excluded": totals["returned_excluded"],
        },
        "categories": category_rows,
        "years": year_rows,
        "sources": source_rows,
    }


def period_label(start_year, end_year):
    if start_year and end_year:
        return f"{start_year}-{end_year}"
    if start_year:
        return f"{start_year}-present"
    if end_year:
        return f"through-{end_year}"
    return "all-years"


def write_outputs(workdir, summary, top):
    output_dir = workdir / "analysis"
    output_dir.mkdir(parents=True, exist_ok=True)
    label = period_label(summary["start_year"], summary["end_year"])
    json_path = output_dir / f"category-summary-{label}.json"
    csv_path = output_dir / f"category-summary-{label}.csv"
    md_path = output_dir / f"category-summary-{label}.md"

    json_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")

    with csv_path.open("w", newline="", encoding="utf-8") as csv_file:
        fieldnames = ["category", "spend", "share", "rows", "orders"]
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        for row in summary["categories"]:
            writer.writerow({name: row[name] for name in fieldnames})

    lines = [
        "# Amazon Order Category Summary",
        "",
        f"- Period: {label}",
        f"- Total spend: {summary['totals']['spend']}",
        f"- Rows analyzed: {summary['totals']['rows']}",
        f"- Returned rows excluded: {summary['totals']['returned_excluded']}",
        "",
        "| Category | Spend | Share | Rows | Orders |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for row in summary["categories"][:top]:
        lines.append(f"| {row['category']} | {row['spend']:.2f} | {row['share']:.2f}% | {row['rows']} | {row['orders']} |")
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return json_path, csv_path, md_path


def parse_args():
    parser = argparse.ArgumentParser(description="Summarize categorized Amazon order history.")
    parser.add_argument("--workdir", type=Path, default=Path(DEFAULT_WORKDIR), help=f"Default: {DEFAULT_WORKDIR}")
    parser.add_argument("--start-year", type=int, help="First year to include, inclusive.")
    parser.add_argument("--end-year", type=int, help="Last year to include, inclusive.")
    parser.add_argument("--top", type=int, default=15, help="Number of top categories to show in console/Markdown. Default: 15")
    parser.add_argument("--category-depth", type=int, default=1, help="Number of breadcrumb levels to group by. Default: 1")
    parser.add_argument("--include-returned", action="store_true", help="Include rows marked is_returned=true.")
    return parser.parse_args()


def main():
    args = parse_args()
    if args.start_year and args.end_year and args.start_year > args.end_year:
        raise SystemExit("--start-year cannot be greater than --end-year")
    if not (args.workdir / "orders").exists():
        raise SystemExit(f"Missing orders directory: {args.workdir / 'orders'}")

    summary = build_summary(args.workdir, args.start_year, args.end_year, args.include_returned, args.category_depth)
    json_path, csv_path, md_path = write_outputs(args.workdir, summary, args.top)

    print("Amazon order analysis complete")
    print(f"rows={summary['totals']['rows']}")
    print(f"spend={summary['totals']['spend']:.2f}")
    print(f"json={json_path}")
    print(f"csv={csv_path}")
    print(f"markdown={md_path}")
    print("top_categories:")
    for row in summary["categories"][: args.top]:
        print(f"  {row['category']}: {row['spend']:.2f} ({row['share']:.2f}%)")


if __name__ == "__main__":
    main()
